BUFFER_SIZE: 1e5  # replay buffer size
BATCH_SIZE: 64  # minibatch size
GAMMA: 0.99  # discount factor
TAU: 1e-3  # for soft update of target parameters
LR: 5e-4  # learning rate
UPDATE_EVERY: 4  # how often to update the network

BANANA_ENVIRONMENT: /home/idriss/IDRISS/Udacity DRL/deep-reinforcement-learning/p1_navigation/Banana_Linux/Banana.x86_64
device: cpu # Possible values cuda or cpu

n_episodes: 1400
max_t: 1000
eps_start: 1.0
eps_end: 0.01
eps_decay: 0.995